title: xTools 用户手册 & 开发者手册
description: xTools 用户手册 & 开发者手册
theme: just-the-docs

url: https://x-tools-author.github.io/x-tools

aux_links_new_tab: true
aux_links:
  访问xTools项目仓库: https://github.com/x-tools-author/x-tools

permalink: pretty

# logo
# logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/logo.ico"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap