title: xTools Project Documentation
description: Comprehensive documentation for the xTools project.
theme: jekyll-theme-cayman
url: https://x-tools-author.github.io/x-tools
baseurl: /x-tools/docs
author:
  name: x-tools-author
  email: x-tools@outlook.com
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
markdown: kramdown
highlighter: rouge