title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote-theme: just-the-docs

url: https://x-tools-author.github.io/x-tools/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs
