name: build-windows
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually
# on:
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build MSVC
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version: [6.8.2]
        arch: [win64_mingw]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          dir: ${{ github.workspace }}
          version: ${{ matrix.version }}
          target: desktop
          arch: ${{ matrix.arch }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          set PATH=${{ github.workspace }}\Qt\Tools\MinGW\bin;%PATH%
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "Ninja" ../
          cmake --build . --target all --config Release
