name: build-test
on:
 push:
   branches:
     - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Windows:
    name: Windows Test
    runs-on: windows-latest
    steps:
      - name: echo
        shell: cmd
        run: |
          echo "hello world"
  Linux:
    name: Ubuntu Test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello world"

